# Server settings
server:
  port: 12140
  context-path: "/promotion/coupon/api"

# Shell settings
shell:
  ssh:
    port: 32140
  auth:
    simple:
      user:
        name: vpclub
        password: 5pC1ub

# SPRING PROFILES
spring:
  dubbo:
    basePackages: cn.vpclub.promotion.coupon.consumer

    application:
      name: vp-promotion-coupon-consumer
      owner: vpclub

    protocol:
      port: 22140

    consumer:
      check: false

    provider:
      timeout: 3000
      retries: 1
      delay: -1

    registry:
      address: nacos://47.104.171.106:8848

  redis:
    database: 3
    host: 172.16.6.202
    password:
    port: 6379

# LOGGING
logging:
    level:
       tk.mybatis: DEBUG

# SystemConfig
config:
    service:
        requestTimeDiff: 6000
producer:
    namesrv: 172.16.6.6:9876
    group  : receive_group
    topic  : couponCodeReceive